version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - cache
    volumes:
      - ./src:/src
    expose:
      - "8000"
    
  db:
    image: postgres:latest
    container_name: ps01

  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
